spring:
  cloud:
    #ribbon重试机制
    loadbalancer:
      retry:
        enabled: true


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  okToRetryOnAllOperations: true

#hystrix
hystrix:
  threadpool:
    default:
      coreSize: 100
  command:
    circuitBreaker:
      #当在配置时间窗口内达到此数量后的失败，进行短路。
      requestVolumeThreshold: 1000

    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            #2分钟熔断 (ReadTimeout+ConnectTimeout) * (1 + MaxAutoRetries) * (1 + MaxAutoRetriesNextServer)
            timeoutInMilliseconds: 120000

